const TYPES = {
    SET_TOKEN: 'SET_TOKEN',

    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',

    REQUEST_ERROR: 'REQUEST_ERROR',
    CHANGE_LOADER: 'CHANGE_LOADER',

    REQUEST_NOTES: 'REQUEST_NOTE',
    FETCH_NOTES: 'FETCH_NOTES',
    REMOVE_NOTE: 'REMOVE_NOTE',
    REQUEST_ADD_NOTE: 'REQUEST_ADD_NOTE',
    REQUEST_REMOVE_NOTE: 'REQUEST_REMOVE_NOTE',
    ADD_NOTE: 'ADD_NOTE',
    REQUEST_COMPLETE_NOTE: 'REQUEST_COMPLETE_NOTE',
    COMPLETE_NOTE: 'COMPLETE_NOTE',
    
    SET_USER_ID: 'SET_USER_ID',
    REQUEST_PROJECTS: 'REQUEST_PROJECTS',
    REQUEST_ADD_PROJECT: 'REQUEST_ADD_PROJECT',
    ADD_PROJECT: 'ADD_PROJECT',
    REQUEST_REMOVE_PROJECT: 'REQUEST_REMOVE_PROJECT',
    REMOVE_PROJECT: 'REMOVE_PROJECT',
    FETCH_PROJECT: 'FETCH_PROJECT',
    SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',
    ADD_USER_TO: 'ADD_USER_TO_PROJECT',
    SUCC_ADDING: 'SUCC_ADDING',
    CLEAR_DATA: 'CLEAR_DATA',
    REQUEST_UPDATE_PROJECT: 'REQUEST_UPDATE_PROJECT',
    CHANGE_SETTINGS: 'CHANGE_SETTINGS',

    REQUEST_CREATE_USER: 'REQUEST_CREATE_USER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REQUEST_LOGIN_USER: 'REQUEST_LOGIN_USER',
    REQUEST_LOGOUT: 'REQUEST_LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REQUEST_PROFILE: 'REQUEST_PROFILE',

    GET_ALL_USERS: 'USER/SAGA/GET_ALL_USERS',
    ACTION_UPDATE_PASS: 'USER/SAGA/ACTION_UPDATE_PASS',
    AUTH_ACTION_PASS_RECOVERY: 'USER/SAGA/AUTH_ACTION_PASS_RECOVERY',
    GET_USER_ACTION: 'USER/SAGA/GET_USER_ACTION',
    UPDATE_USER_DATA: 'USER/SAGA/UPDATE_USER_DATA',
    ONLY_FOR_NOT_AUTHORIZE_USERS: 'USER/SAGA/ONLY_FOR_NOT_AUTHORIZE_USERS',
    HEADER_REQUEST_AUTHORIZE: 'USER/SAGA/HEADER_REQUEST_AUTHORIZE',
    
    CHANGE_PASS_SUCCESS: 'USER/REDUCER/CHANGE_PASS_SUCCESS',
    CHANGE_PASS_ERROR: 'USER/REDUCER/CHANGE_PASS_ERROR',
    GET_USER_SUCCESS: 'USER/REDUCER/GET_USER_SUCCESS',
    GET_USER_ERROR: 'USER/REDUCER/GET_USER_ERROR',
    CLEAR_USER_STORE: 'USER/REDUCER/CLEAR_USER_STORE',
    UPDATE_USER_DATA_SUCCESS: 'USER/REDUCER/UPDATE_USER_DATA_SUCCESS',
    UPDATE_USER_DATA_ERROR: 'USER/REDUCER/UPDATE_USER_DATA_ERROR',
    CLEAR_USER_ERROR: 'USER/REDUCER/CLEAR_USER_ERROR',

}
export default TYPES