const TYPES = {
    SET_TOKEN: 'SET_TOKEN',

    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',

    REQUEST_ERROR: 'REQUEST_ERROR',
    CHANGE_LOADER: 'CHANGE_LOADER',

    REQUEST_NOTES: 'REQUEST_NOTE',
    FETCH_NOTES: 'FETCH_NOTES',
    REMOVE_NOTE: 'REMOVE_NOTE',
    REQUEST_ADD_NOTE: 'REQUEST_ADD_NOTE',
    REQUEST_REMOVE_NOTE: 'REQUEST_REMOVE_NOTE',
    ADD_NOTE: 'ADD_NOTE',
    REQUEST_COMPLETE_NOTE: 'REQUEST_COMPLETE_NOTE',
    COMPLETE_NOTE: 'COMPLETE_NOTE',
    
    SET_USER_ID: 'SET_USER_ID',
    REQUEST_PROJECTS: 'REQUEST_PROJECTS',
    REQUEST_ADD_PROJECT: 'REQUEST_ADD_PROJECT',
    ADD_PROJECT: 'ADD_PROJECT',
    REQUEST_REMOVE_PROJECT: 'REQUEST_REMOVE_PROJECT',
    REMOVE_PROJECT: 'REMOVE_PROJECT',
    FETCH_PROJECT: 'FETCH_PROJECT',
    SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',
    ADD_USER_TO: 'ADD_USER_TO_PROJECT',
    SUCC_ADDING: 'SUCC_ADDING',
    CLEAR_DATA: 'CLEAR_DATA',
    REQUEST_UPDATE_PROJECT: 'REQUEST_UPDATE_PROJECT',
    CHANGE_SETTINGS: 'CHANGE_SETTINGS',

    REQUEST_CREATE_USER: 'REQUEST_CREATE_USER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REQUEST_LOGIN_USER: 'REQUEST_LOGIN_USER',
    REQUEST_LOGOUT: 'REQUEST_LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REQUEST_PROFILE: 'REQUEST_PROFILE',
}
export default TYPES