const TYPES = {
    REQUEST_NOTES: 'REQUEST_NOTE',
    CHANGE_LOADER: 'CHANGE_LOADER',
    FETCH_NOTES: 'FETCH_NOTES',
    REMOVE_NOTE: 'REMOVE_NOTE',
    REQUEST_ADD_NOTE: 'REQUEST_ADD_NOTE',
    REQUEST_REMOVE_NOTE: 'REQUEST_REMOVE_NOTE',
    ADD_NOTE: 'ADD_NOTE',
    REQUEST_COMPLETE_NOTE: 'REQUEST_COMPLETE_NOTE',
    COMPLETE_NOTE: 'COMPLETE_NOTE',
}
export default TYPES